x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/root/.nanobot

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    environment:
      - NANOBOT_BRAIN_OFFICE__URL=http://brain-office:8765
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
  
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
    environment:
      - NANOBOT_BRAIN_OFFICE__URL=http://brain-office:8765

  brain-office:
    build:
      context: ./brain-office
      dockerfile: Dockerfile
    container_name: brain-office
    ports:
      - "8765:8765"
    restart: unless-stopped
